version: "3.7"

services:
    tfn-server:
        hostname: tfn_server
        container_name: tfn_server
        image:  nwnxee/unified:9914bd2
        env_file:            
            - ${PWD-.}/config/common.env
            - ${PWD-.}/config/nwserver.env
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
        ports:
            - "5121:5121/udp"